### ISSUE TITLE
Can't use ! helper methods for enums

### ISSUE THREAD

**Issue by Jellyfishboy** [CristiRazvi/enum_attributes_validation#6]
If I use the update method for enums, it returns an error:

`ActiveRecord::RecordInvalid: Validation failed: Status can't be 1. Valid values are: active, archived`

Model:

```ruby
enum status: [:active, :archived]
validate_enum_attributes :status
```

Controller action: 

```ruby
def destroy
     set_vehicle
     @vehicle.archived!
     redirect_to admin_vehicles_path, notice: 'Successfully archived the vehicle'
end
```

**Comment by CristiRazvi** [comment]
@Jellyfishboy i added tests for bang methods on enum attributes and they pass. could you provide more info on the issue? what values does `@vehicle` have before trying `@vehicle.archived!`?

you can see the tests here
https://github.com/CristiRazvi/enum_attributes_validation/commit/199522b1fdf325073b3eab321aa72ce83ae7d015

**Comment by Jellyfishboy** [comment]
@CristiRazvi Thanks for your response.

Model:
```ruby
class Store < ApplicationRecord

    enum status: [:active, :archived]
    enum dropbox_setup: [:pending, :completed, :failed], _prefix: true

    validate_enum_attributes :status, :dropbox_setup
end
```


As you can see from the Rails console screenshot and the model set up, I am unable to use the bang methods without an error occurring.

**Rails version: 5.2**
**Ruby version 2.4.4**

**Comment by Jellyfishboy** [comment]
@CristiRazvi I ended up implementing my own solution, thanks anyway.

**Comment by jjercTK** [comment]
this is still an issue in the gem
